### ISSUE TITLE
It is possible to put the game into a weird state

### ISSUE THREAD

**Issue by InsiderPhD** [melair/ktane#1]
If the cables are not disconnected in between basked the game is put into a weird stagd

**Comment by melair** [comment]
This is solved by 9810a73be7e14913d6606e7de681d0970c89e883, the issue isn't infact inbetween games as the actual MCU has to be restarted and its RAM is wiped on start. It's actually an oddity to do with changing resistances when a cable is touched/wiggled. This change makes it not care about cables "changing" colour during the game, only if they are removed outright.
